require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7.1

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false
